### ISSUE TITLE
Refactor ActionConfirmation to a popover instead of Modal.

### ISSUE THREAD

**Issue by Eidsheimen** [EgdeConsulting/NATSAdminportal#118]
Refactor ActionConfirmation-component so that it is a popover instead of a modal. 
See: https://chakra-ui.com/docs/components/popover

The action confirmation is currently (10/3-23) only used in the context of publishing a message, but will probably be used for more. 

Acceptance criteria:

1. Alter the component so it uses the popover instead.
2. Verify that it still works.

**Comment by Eidsheimen** [comment]
Look at this if time.

**Comment by TobiasGunther** [comment]
We decided to keep the modal, closing issue.
