### ISSUE TITLE
Improve export structure

### ISSUE THREAD

**Issue by TobiasGunther** [EgdeConsulting/NATSAdminportal#74]
Acceptance criteria:

1. Add index.tsx structure in frontend so that component imports all can happen via `import {...} from "components";` instead of `import {...} from "./" or "./components"`
2. Do the same for "routes", "styles" and "types" folders
3. Verify that everything works

**Comment by Eidsheimen** [comment]
Found a package from https://github.com/aleclarson/vite-tsconfig-paths
